NoPermission: "&cYou don't have permission to perform this command."
FreezeCmdUsage: "&bUsage: &3/%command% <player>"
FrozenPrefix: "&b[&4Frozen&b]&f"
FreezeSuccess: "&bYou have successfully frozen &3%player%"
FrozenMessage: "&c&lYOU HAVE BEEN FROZEN! PLEASE JOIN ts.dreampvp.pw IN 5 MINUTES OR YOU WILL BE BANNED!"
FrozenAlert: "&b[S] &3%frozen% &bhas been frozen by &3%freezer%&b."
UnFreezeSuccess: "&bYou have successfully unfrozen &3%player%"
UnFrozenAlert: "&b[S] &3%frozen% &bhas been unfrozen by &3%freezer%&b."
FreezeCommandDeny: "&cYou are not allowed to perform this command while frozen"
LeftWhileFrozen: "&b[S] &3%player%&b left while frozen"
StaffModeEnableSelf: "&eYou have modmoded"
StaffModeEnableOthers: "&7&o[%player%: &ehas modmoded&7&o]"
StaffModeDisableSelf: "&eYou have unmodmoded"
StaffModeDisableOthers: "&7&o[%player%: &ehas unmodmoded&7&o]"
SudoUsage: "&bUsage: &3/%command% <player> <message>"
PingUsage: "&bUsage: &3/%command% <player>"
OwnPing: "&bYour ping: &3%ping%"
OtherPing: "&3%player%&b's ping: &3%ping%"
SetPlayersUsage: "&bUsage: &3/%command% <slots>"
MaxPlayersSet: "&eSet max slots to %slots%"
InvseeUsage: "&bUsage: &3/%command% <player> [-i]"
TeleportUsage: "&bUsage: /%command% <player>"
TeleportHereUsage: "&bUsage: /%command% <player>"
TeleportSelf: "&eYou have been teleported to %player%"
TeleportHereSelf: "&eYou have teleported %player% to you"
TeleportOthers: "&7&o[%sender%: &ehas teleported to %player%&7&o]"
TeleportHereOthers: "&7&o[%sender%: &ehas teleported %player% to himself&7&o]"
TeleportAllSelf: "&eYou have teleported everyone to yourself."
TeleportAllOthers: "&7&o[%sender%: &ehas teleported everyone to himself&7&o]"
FlyUsage: "&bUsage: /%command% <player>"
FlyEnabledSelf: "&eYou have enabled your flight."
FlyDisabledSelf: "&eYou have disabled your flight."
FlyEnabledOther: "&eYou have enabled %player%'s flight."
FlyDisabledOther: "&eYou have disabled %player%'s flight."